//! `chorale-derive`: `#[derive(TableRow)]` for automatic `ColumnDef` generation.
//!
//! Apply to a concrete (non-generic) struct whose fields you want to expose as
//! chorale table columns:
//!
//! ```rust,ignore
//! use chorale_derive::TableRow;
//!
//! #[derive(TableRow, Clone, PartialEq)]
//! pub struct Employee {
//!     pub id: u32,
//!     pub name: String,
//!     pub salary: f64,
//!     pub active: bool,
//!     #[chorale(skip)]
//!     pub internal_token: String,
//! }
//!
//! // Generated:
//! // impl Employee {
//! //     pub fn chorale_columns() -> Vec<chorale_core::ColumnDef<Employee>> { ... }
//! // }
//! ```
//!

extern crate proc_macro;

use proc_macro::TokenStream;
use proc_macro2::{Span, TokenStream as TokenStream2};
use quote::quote;
use syn::{
    parse_macro_input, spanned::Spanned, Data, DeriveInput, Error, Field, Fields, GenericParam,
    Lit, Type, TypePath,
};

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/// Derive macro that generates a `chorale_columns() -> Vec<ColumnDef<Self>>`
/// inherent method on the annotated struct.
#[proc_macro_derive(TableRow, attributes(chorale))]
pub fn table_row_derive(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    expand(input)
        .unwrap_or_else(Error::into_compile_error)
        .into()
}

// ---------------------------------------------------------------------------
// Field configuration (parsed from #[chorale(...)] attributes)
// ---------------------------------------------------------------------------

#[derive(Default)]
struct FieldConfig {
    skip: bool,
    header: Option<String>,
    initial_width: Option<f64>,
    sortable_override: Option<bool>,
    filter_override: Option<FilterOverride>,
    align_override: Option<String>,
}

enum FilterOverride {
    None,
    Text,
    Boolean,
    DateRange,
    MultiSelect(Vec<String>),
}

// ---------------------------------------------------------------------------
// Main expansion
// ---------------------------------------------------------------------------

fn expand(input: DeriveInput) -> Result<TokenStream2, Error> {
    // Only structs.
    let Data::Struct(struct_data) = input.data else {
        return Err(Error::new(
            input.ident.span(),
            "#[derive(TableRow)] only supports structs",
        ));
    };

    // Generic structs not supported.
    let bad_param = input.generics.params.iter().find(|p| {
        matches!(
            p,
            GenericParam::Type(_) | GenericParam::Lifetime(_) | GenericParam::Const(_)
        )
    });
    if let Some(p) = bad_param {
        return Err(Error::new(
            p.span(),
            "#[derive(TableRow)] does not support generic structs; use the explicit ColumnDef API instead",
        ));
    }

    // Only named-field structs.
    let Fields::Named(named_fields) = struct_data.fields else {
        return Err(Error::new(
            input.ident.span(),
            "#[derive(TableRow)] only supports structs with named fields",
        ));
    };

    let struct_name = &input.ident;

    // Parse and generate each column definition.
    let mut col_defs: Vec<TokenStream2> = Vec::new();
    for field in &named_fields.named {
        let cfg = parse_field_config(field)?;
        if cfg.skip {
            continue;
        }
        col_defs.push(generate_col_def(field, &cfg));
    }

    // Bounds check: emit a const that fails if TRow doesn't satisfy Clone + PartialEq.
    let bounds_check = quote! {
        const _: fn() = || {
            fn _assert_bounds<T: ::core::clone::Clone + ::core::cmp::PartialEq>() {}
            _assert_bounds::<#struct_name>();
        };
    };

    Ok(quote! {
        #bounds_check

        impl #struct_name {
            /// Returns the `ColumnDef` list for this struct, generated by `#[derive(TableRow)]`.
            ///
            /// Pass the result to `TableState::new(rows, Self::chorale_columns())`.
            #[must_use]
            #[allow(
                clippy::cast_possible_truncation,
                clippy::cast_possible_wrap,
                clippy::cast_precision_loss,
                clippy::cast_sign_loss,
            )]
            pub fn chorale_columns() -> ::std::vec::Vec<::chorale_core::ColumnDef<Self>> {
                vec![
                    #(#col_defs),*
                ]
            }
        }
    })
}

// ---------------------------------------------------------------------------
// Attribute parsing
// ---------------------------------------------------------------------------

fn parse_field_config(field: &Field) -> Result<FieldConfig, Error> {
    let mut cfg = FieldConfig::default();

    for attr in &field.attrs {
        if !attr.path().is_ident("chorale") {
            continue;
        }
        // Parse #[chorale(key, key = value, ...)]
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("skip") {
                cfg.skip = true;
                return Ok(());
            }

            if meta.path.is_ident("header") {
                let value = meta.value()?;
                let s: syn::LitStr = value.parse()?;
                cfg.header = Some(s.value());
                return Ok(());
            }

            if meta.path.is_ident("initial_width") {
                let value = meta.value()?;
                let lit: Lit = value.parse()?;
                cfg.initial_width = Some(lit_to_f64(&lit, meta.path.span())?);
                return Ok(());
            }

            if meta.path.is_ident("sortable") {
                let value = meta.value()?;
                let lit: syn::LitBool = value.parse()?;
                cfg.sortable_override = Some(lit.value);
                return Ok(());
            }

            if meta.path.is_ident("filter") {
                let value = meta.value()?;
                let s: syn::LitStr = value.parse()?;
                cfg.filter_override = Some(match s.value().as_str() {
                    "none" | "None" => FilterOverride::None,
                    "Text" | "text" => FilterOverride::Text,
                    "Boolean" | "boolean" => FilterOverride::Boolean,
                    "Date" | "DateRange" | "date" => FilterOverride::DateRange,
                    "MultiSelect" | "multiselect" => {
                        // options must come separately; default to empty until overridden
                        FilterOverride::MultiSelect(vec![])
                    }
                    other => {
                        return Err(meta.error(format!(
                            "unknown filter kind `{other}`; expected one of: \
                             none, Text, Boolean, Date, MultiSelect"
                        )))
                    }
                });
                return Ok(());
            }

            if meta.path.is_ident("options") {
                // #[chorale(options = ["a", "b", "c"])]
                // Parse as a bracketed list of string literals.
                let value = meta.value()?;
                let arr: syn::ExprArray = value.parse()?;
                let mut opts = Vec::new();
                for elem in &arr.elems {
                    match elem {
                        syn::Expr::Lit(syn::ExprLit {
                            lit: Lit::Str(s), ..
                        }) => opts.push(s.value()),
                        _ => {
                            return Err(Error::new(elem.span(), "options must be string literals"))
                        }
                    }
                }
                // Update or create the MultiSelect override.
                cfg.filter_override = Some(FilterOverride::MultiSelect(opts));
                return Ok(());
            }

            if meta.path.is_ident("align") {
                let value = meta.value()?;
                let s: syn::LitStr = value.parse()?;
                cfg.align_override = Some(s.value());
                return Ok(());
            }

            Err(meta.error(format!(
                "unknown chorale attribute `{}`",
                meta.path
                    .get_ident()
                    .map_or_else(|| "?".to_owned(), ToString::to_string)
            )))
        })?;
    }

    Ok(cfg)
}

fn lit_to_f64(lit: &Lit, span: Span) -> Result<f64, Error> {
    match lit {
        Lit::Float(f) => f.base10_parse().map_err(|e| Error::new(span, e)),
        Lit::Int(i) => i
            .base10_parse::<i64>()
            .map(|n| {
                #[allow(clippy::cast_precision_loss)]
                let f = n as f64;
                f
            })
            .map_err(|e| Error::new(span, e)),
        _ => Err(Error::new(span, "expected a numeric literal")),
    }
}

// ---------------------------------------------------------------------------
// Type inference
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq)]
enum InferredKind {
    Text,
    Integer,
    Float,
    Boolean,
    Date,
    OptionText,
    OptionInteger,
    OptionFloat,
    OptionBoolean,
    OptionDate,
    OptionDisplay,
    Display,
}

impl InferredKind {
    fn is_numeric(self) -> bool {
        matches!(
            self,
            Self::Integer | Self::Float | Self::OptionInteger | Self::OptionFloat
        )
    }
}

fn infer_kind(ty: &Type) -> InferredKind {
    let Type::Path(TypePath { path, .. }) = ty else {
        return InferredKind::Display;
    };

    let Some(last) = path.segments.last() else {
        return InferredKind::Display;
    };

    let ident = last.ident.to_string();

    // Check Option<T>
    if ident == "Option" {
        if let syn::PathArguments::AngleBracketed(args) = &last.arguments {
            if let Some(syn::GenericArgument::Type(inner)) = args.args.first() {
                return match infer_kind(inner) {
                    InferredKind::Text => InferredKind::OptionText,
                    InferredKind::Integer => InferredKind::OptionInteger,
                    InferredKind::Float => InferredKind::OptionFloat,
                    InferredKind::Boolean => InferredKind::OptionBoolean,
                    InferredKind::Date => InferredKind::OptionDate,
                    _ => InferredKind::OptionDisplay,
                };
            }
        }
        return InferredKind::OptionDisplay;
    }

    match ident.as_str() {
        "String" => InferredKind::Text,
        "u8" | "u16" | "u32" | "u64" | "u128" | "usize" | "i8" | "i16" | "i32" | "i64" | "i128"
        | "isize" => InferredKind::Integer,
        "f32" | "f64" => InferredKind::Float,
        "bool" => InferredKind::Boolean,
        "NaiveDate" => {
            if cfg!(feature = "chrono") {
                InferredKind::Date
            } else {
                InferredKind::Display
            }
        }
        _ => InferredKind::Display,
    }
}

// ---------------------------------------------------------------------------
// Code generation per field
// ---------------------------------------------------------------------------

fn generate_col_def(field: &Field, cfg: &FieldConfig) -> TokenStream2 {
    let Some(field_name) = field.ident.as_ref() else {
        unreachable!("named struct fields always have idents")
    };
    let field_name_str = field_name.to_string();

    // Header: attribute override → Title Case of field name
    let header_str = cfg
        .header
        .clone()
        .unwrap_or_else(|| snake_to_title(&field_name_str));

    let kind = infer_kind(&field.ty);

    // Accessor
    let accessor = build_accessor(field_name, kind);

    // Sortable: default true for all types the core can sort
    let sortable = cfg.sortable_override.unwrap_or(true);

    // Filter
    let filter_tokens = build_filter(cfg, kind);

    // Alignment
    let align_tokens = build_align(cfg, kind);

    // Initial width
    let width_tokens = if let Some(w) = cfg.initial_width {
        quote! { .initial_width(#w) }
    } else {
        quote! {}
    };

    let col_id = quote! { ::chorale_core::ColumnId(#field_name_str) };

    let sortable_tokens = if sortable {
        quote! { .sortable() }
    } else {
        quote! {}
    };

    quote! {
        ::chorale_core::ColumnDef::new(
            #col_id,
            #header_str,
            |r: &Self| #accessor,
        )
        #sortable_tokens
        #filter_tokens
        #align_tokens
        #width_tokens
    }
}

fn build_accessor(field_name: &syn::Ident, kind: InferredKind) -> TokenStream2 {
    match kind {
        InferredKind::Text => quote! {
            ::chorale_core::CellValue::Text(r.#field_name.clone())
        },
        InferredKind::Integer => quote! {
            ::chorale_core::CellValue::Integer(r.#field_name as i64)
        },
        InferredKind::Float => quote! {
            ::chorale_core::CellValue::Float(r.#field_name as f64)
        },
        InferredKind::Boolean => quote! {
            ::chorale_core::CellValue::Boolean(r.#field_name)
        },
        InferredKind::Date => quote! {
            ::chorale_core::CellValue::Date(r.#field_name)
        },
        InferredKind::OptionText => quote! {
            r.#field_name.as_ref().map_or(
                ::chorale_core::CellValue::Empty,
                |v| ::chorale_core::CellValue::Text(v.clone()),
            )
        },
        InferredKind::OptionInteger => quote! {
            r.#field_name.map_or(
                ::chorale_core::CellValue::Empty,
                |v| ::chorale_core::CellValue::Integer(v as i64),
            )
        },
        InferredKind::OptionFloat => quote! {
            r.#field_name.map_or(
                ::chorale_core::CellValue::Empty,
                |v| ::chorale_core::CellValue::Float(v as f64),
            )
        },
        InferredKind::OptionBoolean => quote! {
            r.#field_name.map_or(
                ::chorale_core::CellValue::Empty,
                ::chorale_core::CellValue::Boolean,
            )
        },
        InferredKind::OptionDate => quote! {
            r.#field_name.map_or(
                ::chorale_core::CellValue::Empty,
                ::chorale_core::CellValue::Date,
            )
        },
        InferredKind::OptionDisplay => quote! {
            r.#field_name.as_ref().map_or(
                ::chorale_core::CellValue::Empty,
                |v| ::chorale_core::CellValue::Text(v.to_string()),
            )
        },
        InferredKind::Display => quote! {
            ::chorale_core::CellValue::Text(r.#field_name.to_string())
        },
    }
}

fn build_filter(cfg: &FieldConfig, kind: InferredKind) -> TokenStream2 {
    let filter = if let Some(fo) = &cfg.filter_override {
        match fo {
            FilterOverride::None => return quote! {},
            FilterOverride::Text => quote! {
                ::chorale_core::FilterKind::Text
            },
            FilterOverride::Boolean => quote! {
                ::chorale_core::FilterKind::Boolean
            },
            FilterOverride::DateRange => quote! {
                ::chorale_core::FilterKind::DateRange
            },
            FilterOverride::MultiSelect(opts) => quote! {
                ::chorale_core::FilterKind::MultiSelect {
                    options: vec![#(#opts.to_owned()),*],
                }
            },
        }
    } else {
        // Inferred
        match kind {
            InferredKind::Text | InferredKind::OptionText => quote! {
                ::chorale_core::FilterKind::Text
            },
            InferredKind::Boolean | InferredKind::OptionBoolean => quote! {
                ::chorale_core::FilterKind::Boolean
            },
            InferredKind::Date | InferredKind::OptionDate => quote! {
                ::chorale_core::FilterKind::DateRange
            },
            // Numeric and Display: no filter by default.
            _ => return quote! {},
        }
    };
    quote! { .filter(#filter) }
}

fn build_align(cfg: &FieldConfig, kind: InferredKind) -> TokenStream2 {
    let align = if let Some(a) = &cfg.align_override {
        match a.as_str() {
            "Left" | "left" => quote! { ::chorale_core::Alignment::Left },
            "Center" | "center" => quote! { ::chorale_core::Alignment::Center },
            "Right" | "right" => quote! { ::chorale_core::Alignment::Right },
            _ => return quote! {},
        }
    } else {
        // Right-align numeric columns by default.
        if kind.is_numeric() {
            quote! { ::chorale_core::Alignment::Right }
        } else {
            return quote! {};
        }
    };
    quote! { .alignment(#align) }
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

fn snake_to_title(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

// ---------------------------------------------------------------------------
// Tests (compile-time expansion is tested via trybuild/integration tests)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::snake_to_title;

    #[test]
    fn snake_to_title_basic() {
        assert_eq!(snake_to_title("due_date"), "Due Date");
        assert_eq!(snake_to_title("customer"), "Customer");
        assert_eq!(snake_to_title("first_last_name"), "First Last Name");
        assert_eq!(snake_to_title("id"), "Id");
    }

    #[test]
    fn snake_to_title_empty() {
        assert_eq!(snake_to_title(""), "");
    }
}
